### ISSUE TITLE
bug in edp.py

### ISSUE THREAD

**Issue by rihal** [TheGandril/EPaperReader#4]
There is a bug in line 38 of edp.py which causes the display to shift the columns of the image:

upload_header_command=[0x20,0x01,0x00,0x0F] # packet size is 16 bytes

changing the line to:
upload_header_command=[0x20,0x01,0x00,16] # packet size is 16 bytes
should fix the problem.

**Comment by Ceruleous** [comment]
Thank you for submitting this bug report. I would like to  perform confirmation tests before closing this issue.
